-- Dashboard de Marketplaces — snapshot diário de métricas que NÃO existem no banco
-- e só vêm da API do Mercado Livre (visitas, perguntas, gasto em ADS).
-- Alimentada pelo job APScheduler tasks/sync_marketplace_metrics.py (4x/dia).
-- Cada linha = métricas da conta no dia (BRT). Upsert por (account_id, metric_date).
-- Pedidos/Faturamento NÃO entram aqui — são calculados ao vivo da tabela orders.
-- Idempotente: bloco anônimo PL/SQL captura ORA-00955 (objeto já existe).

DECLARE
  e_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE marketplace_metrics_daily (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      account_id NUMBER NOT NULL,
      metric_date DATE NOT NULL,                 -- dia comercial em BRT
      visits NUMBER DEFAULT 0 NOT NULL,          -- ML items_visits/time_window
      questions_total NUMBER DEFAULT 0 NOT NULL, -- perguntas criadas no dia
      questions_unanswered NUMBER DEFAULT 0 NOT NULL,
      ads_cost NUMBER(15,2) DEFAULT 0 NOT NULL,  -- gasto product_ads no dia
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT fk_mmd_account FOREIGN KEY (account_id)
        REFERENCES marketplace_accounts(id) ON DELETE CASCADE
    )
  ]';
EXCEPTION
  WHEN e_obj_exists THEN NULL;
END;
/

-- Chave de upsert: uma linha por conta por dia.
DECLARE
  e_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uq_mmd_account_date ON marketplace_metrics_daily(account_id, metric_date)';
EXCEPTION
  WHEN e_obj_exists THEN NULL;
END;
/

-- Acelera os SUMs por janela de data no endpoint do dashboard.
DECLARE
  e_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ix_mmd_date ON marketplace_metrics_daily(metric_date)';
EXCEPTION
  WHEN e_obj_exists THEN NULL;
END;
/

-- Acelera as agregações por janela de data na tabela orders (matriz do dashboard).
DECLARE
  e_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ix_orders_dropshipper_created ON orders(dropshipper_id, created_at)';
EXCEPTION
  WHEN e_obj_exists THEN NULL;
END;
/

COMMIT;
