-- Configuração por marketplace (Super Admin) — 1 linha por marketplace.
-- settings_json (CLOB) guarda config flexível (formatos de mídia, etc.) para
-- permitir adicionar campos sem nova migration. NÃO guardar credenciais aqui
-- (OAuth fica em marketplace_accounts; chaves de IA na config de IA).
-- Idempotente: bloco anônimo PL/SQL captura ORA-00955 (objeto já existe).

DECLARE
  e_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE marketplace_settings (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      marketplace VARCHAR2(20) NOT NULL,   -- mercadolivre|shopee|amazon|tiktok|magalu
      settings_json CLOB,                  -- JSON flexível
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN e_obj_exists THEN NULL;
END;
/

DECLARE
  e_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE
    'CREATE UNIQUE INDEX uq_marketplace_settings_mp ON marketplace_settings(marketplace)';
EXCEPTION
  WHEN e_obj_exists THEN NULL;
END;
/

COMMIT;
