-- Fase C: geração de clip/vídeo por IA (Veo).
-- 1) media_video_model na config de IA (modelo de vídeo, ex.: veo-3.1-fast-generate-preview).
-- 2) media_clip_jobs: persiste a geração assíncrona (operation do Veo) para não
--    perder o resultado pago em reload, permitir consultar status e listar clips.
-- Idempotente (ORA-1430 coluna já existe / ORA-955 objeto já existe).

DECLARE
  e_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_col_exists, -1430);
BEGIN
  EXECUTE IMMEDIATE q'[ALTER TABLE ai_configs ADD media_video_model VARCHAR2(100) DEFAULT 'veo-3.1-fast-generate-preview']';
EXCEPTION WHEN e_col_exists THEN NULL;
END;
/

DECLARE
  e_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE media_clip_jobs (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id NUMBER,
      operation VARCHAR2(500) NOT NULL,   -- nome da operação long-running do Veo
      marketplace VARCHAR2(20),
      prompt VARCHAR2(1100),
      status VARCHAR2(20) DEFAULT 'running' NOT NULL,  -- running | done | failed
      video_url VARCHAR2(1000),
      error VARCHAR2(500),
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN e_obj_exists THEN NULL;
END;
/

DECLARE
  e_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ix_clip_jobs_user ON media_clip_jobs(user_id, created_at)';
EXCEPTION
  WHEN e_obj_exists THEN NULL;
END;
/

COMMIT;
