-- Atendimento: Reclamações (claims pós-venda do Mercado Livre) por conta CMIG.
-- Persiste a reclamação, as mensagens dos 2 canais (comprador/mediador), o
-- histórico de ações e os status. Distinto de `returns` (devolução FÍSICA do
-- galpão) — ver ADR-0007.
-- Tabela auxiliar message_templates ("Mensagens Prontas").
-- Idempotente (ORA-955 objeto já existe).

-- 1) claims --------------------------------------------------------------------
DECLARE
  e_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE claims (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      marketplace_account_id NUMBER NOT NULL,
      platform VARCHAR2(30) DEFAULT 'mercadolivre' NOT NULL,
      platform_claim_id VARCHAR2(50) NOT NULL,
      resource_id VARCHAR2(50),
      order_id NUMBER,                       -- Order interno (quando casar)
      platform_order_id VARCHAR2(50),
      status VARCHAR2(20),                   -- opened | closed
      stage VARCHAR2(20),                    -- claim | dispute | recontact | stale | none
      claim_type VARCHAR2(30),              -- mediations | return | fulfillment | ml_case
      reason_id VARCHAR2(30),               -- PNR | PDD | CS ...
      reason_label VARCHAR2(200),
      fulfilled NUMBER(1) DEFAULT 0,
      quantity_type VARCHAR2(20),           -- total | partial
      affects_reputation VARCHAR2(20),      -- affected | not_affected | not_applies
      title VARCHAR2(500),
      description CLOB,
      problem VARCHAR2(500),
      buyer_platform_id VARCHAR2(50),
      buyer_nickname VARCHAR2(200),
      item_id VARCHAR2(50),
      item_title VARCHAR2(500),
      quantity NUMBER,
      amount NUMBER(15,2),
      available_actions_json CLOB,
      has_return NUMBER(1) DEFAULT 0,
      related_return_id VARCHAR2(50),
      resolution_json CLOB,
      due_date TIMESTAMP,
      ml_date_created TIMESTAMP,
      ml_last_updated TIMESTAMP,
      last_message_at TIMESTAMP,
      synced_at TIMESTAMP DEFAULT SYSTIMESTAMP,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION WHEN e_obj_exists THEN NULL;
END;
/

DECLARE
  e_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX ux_claims_platform ON claims(platform_claim_id, marketplace_account_id)';
EXCEPTION WHEN e_obj_exists THEN NULL;
END;
/

DECLARE
  e_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ix_claims_account ON claims(marketplace_account_id, status)';
EXCEPTION WHEN e_obj_exists THEN NULL;
END;
/

-- 2) claim_messages ------------------------------------------------------------
DECLARE
  e_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE claim_messages (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      claim_id NUMBER NOT NULL,
      channel VARCHAR2(20) NOT NULL,        -- complainant | mediator
      sender_role VARCHAR2(20),             -- complainant | respondent | mediator
      text_content CLOB,
      translated_text CLOB,
      attachments_json CLOB,
      status VARCHAR2(20),                  -- available | blocked
      stage VARCHAR2(20),
      platform_hash VARCHAR2(200),
      is_read NUMBER(1) DEFAULT 0 NOT NULL,
      sent_at TIMESTAMP,
      synced_at TIMESTAMP DEFAULT SYSTIMESTAMP,
      ai_suggested_text CLOB
    )
  ]';
EXCEPTION WHEN e_obj_exists THEN NULL;
END;
/

DECLARE
  e_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX ux_claim_msg_hash ON claim_messages(platform_hash)';
EXCEPTION WHEN e_obj_exists THEN NULL;
END;
/

DECLARE
  e_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ix_claim_msgs_claim ON claim_messages(claim_id, channel)';
EXCEPTION WHEN e_obj_exists THEN NULL;
END;
/

-- 3) claim_actions (histórico) -------------------------------------------------
DECLARE
  e_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE claim_actions (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      claim_id NUMBER NOT NULL,
      action_name VARCHAR2(60),
      player_role VARCHAR2(20),
      claim_stage VARCHAR2(20),
      claim_status VARCHAR2(20),
      label_pt VARCHAR2(200),
      triggered_by_user_id NUMBER,          -- quem disparou (ação local) — auditoria
      date_created TIMESTAMP,
      synced_at TIMESTAMP DEFAULT SYSTIMESTAMP
    )
  ]';
EXCEPTION WHEN e_obj_exists THEN NULL;
END;
/

DECLARE
  e_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ix_claim_actions_claim ON claim_actions(claim_id, date_created)';
EXCEPTION WHEN e_obj_exists THEN NULL;
END;
/

-- 4) message_templates ("Mensagens Prontas") -----------------------------------
DECLARE
  e_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE message_templates (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cmig_id NUMBER,                        -- escopo CMIG (NULL = do usuário)
      user_id NUMBER,
      title VARCHAR2(200) NOT NULL,
      body CLOB NOT NULL,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION WHEN e_obj_exists THEN NULL;
END;
/

DECLARE
  e_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ix_msg_templates_scope ON message_templates(cmig_id, user_id)';
EXCEPTION WHEN e_obj_exists THEN NULL;
END;
/

COMMIT;
