-- 102_competitor_analysis.sql — Estudos de Análise de Concorrência (ML + IA)
-- Persiste cada estudo por produto PG/CMIG: prompt do usuário, resultado (JSON
-- reutilizável), anotações (memória p/ estudos futuros) e status do job. Idempotente.

DECLARE
  e_tab_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_tab_exists, -955);
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE competitor_analyses (
      id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      requester_user_id   NUMBER        REFERENCES users(id),
      product_type        VARCHAR2(10)  NOT NULL,
      product_id          NUMBER        NOT NULL,
      account_id          NUMBER        REFERENCES marketplace_accounts(id),
      desired_margin_pct  NUMBER(6,2),
      status              VARCHAR2(20)  DEFAULT ''running'' NOT NULL,
      progress_step       VARCHAR2(160),
      user_prompt         CLOB,
      result_json         CLOB,
      notes               CLOB,
      error               VARCHAR2(2000),
      created_at          TIMESTAMP     DEFAULT SYSTIMESTAMP,
      finished_at         TIMESTAMP
    )
  ';
EXCEPTION WHEN e_tab_exists THEN NULL;
END;
/

DECLARE
  e_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_compan_product ON competitor_analyses(product_type, product_id)';
EXCEPTION WHEN e_exists THEN NULL;
END;
/
