-- Migration 116: Emissão própria de NF-e (SEFAZ direto) — parte 2.
--  (a) colunas de protocolo/status SEFAZ em invoices;
--  (b) tabela invoice_sefaz_logs (append-only, retenção 5 anos, imutável via trigger);
--  (c) tabela dfe_recebidos (Distribuição de DFe própria — substitui o pull do Focus).
-- Aditiva, nullable e idempotente. As colunas focus_* de invoices permanecem (legacy).

-- (a) invoices: protocolo de autorização + status SEFAZ + ambiente + provedor de emissão
DECLARE
  e_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_col_exists, -1430);

  PROCEDURE add_col(p_col VARCHAR2, p_def VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE invoices ADD (' || p_col || ' ' || p_def || ')';
  EXCEPTION WHEN e_col_exists THEN NULL;
  END;
BEGIN
  add_col('auth_protocol',     'VARCHAR2(20)');   -- nProt da autorização (cStat=100)
  add_col('sefaz_cstat',       'VARCHAR2(4)');    -- último cStat da nota
  add_col('sefaz_xmotivo',     'VARCHAR2(255)');  -- último xMotivo
  add_col('environment',       'VARCHAR2(12)');   -- ambiente fixado na emissão: homolog | production
  add_col('emission_provider', 'VARCHAR2(10) DEFAULT ''focus''');  -- focus | sefaz
  DBMS_OUTPUT.PUT_LINE('Colunas de protocolo SEFAZ adicionadas a invoices.');
END;
/

-- (b) invoice_sefaz_logs — log bruto request/response SOAP (auditoria fiscal, 5 anos)
DECLARE
  e_table_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_table_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE invoice_sefaz_logs (
      id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      invoice_id        NUMBER,
      cmig_id           NUMBER NOT NULL,
      operation         VARCHAR2(40) NOT NULL,   -- autorizacao | consulta | cancelamento | cce | status | distribuicao
      cstat             VARCHAR2(4),
      xmotivo           VARCHAR2(255),
      payload_request   CLOB,
      payload_response  CLOB,
      created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT fk_sefaz_log_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id)
    )
  ]';
  EXECUTE IMMEDIATE 'CREATE INDEX idx_sefaz_log_invoice ON invoice_sefaz_logs(invoice_id, created_at)';
  EXECUTE IMMEDIATE 'CREATE INDEX idx_sefaz_log_cmig ON invoice_sefaz_logs(cmig_id, created_at)';
  DBMS_OUTPUT.PUT_LINE('Tabela invoice_sefaz_logs criada.');
EXCEPTION
  WHEN e_table_exists THEN
    DBMS_OUTPUT.PUT_LINE('Tabela invoice_sefaz_logs ja existe, continuando.');
END;
/

-- Trigger append-only: log SEFAZ é imutável após INSERT (defesa fiscal).
CREATE OR REPLACE TRIGGER trg_sefaz_log_immutable
BEFORE UPDATE OR DELETE ON invoice_sefaz_logs
BEGIN
  RAISE_APPLICATION_ERROR(-20007,
    'Tabela imutavel: UPDATE/DELETE proibido por politica fiscal (invoice_sefaz_logs)');
END;
/

-- (c) dfe_recebidos — Distribuição de DFe própria (NSU por CMIG; resumo e/ou XML completo)
DECLARE
  e_table_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_table_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE dfe_recebidos (
      id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cmig_id          NUMBER NOT NULL,
      nsu              VARCHAR2(20) NOT NULL,
      chave            VARCHAR2(44),
      schema_dfe       VARCHAR2(60),                  -- ex.: resNFe_v1.01 | procNFe_v4.00
      resumo_json      CLOB,                          -- resumo (resNFe) quando só vem o resumo
      xml              CLOB,                          -- XML completo (procNFe) quando disponível
      manifestacao     VARCHAR2(20) DEFAULT 'pending',-- pending | ciencia | confirmacao | desconhecimento | nao_realizada
      manifestacao_at  TIMESTAMP,
      invoice_id       NUMBER,                        -- Invoice de entrada criada a partir deste DFe
      criado_em        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT uq_dfe_cmig_nsu UNIQUE (cmig_id, nsu),
      CONSTRAINT fk_dfe_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id)
    )
  ]';
  EXECUTE IMMEDIATE 'CREATE INDEX idx_dfe_rec_chave ON dfe_recebidos(chave)';
  EXECUTE IMMEDIATE 'CREATE INDEX idx_dfe_rec_cmig ON dfe_recebidos(cmig_id, criado_em)';
  DBMS_OUTPUT.PUT_LINE('Tabela dfe_recebidos criada.');
EXCEPTION
  WHEN e_table_exists THEN
    DBMS_OUTPUT.PUT_LINE('Tabela dfe_recebidos ja existe, continuando.');
END;
/
