-- Migration 119: convites de colaborador por e-mail (cadastro + aprovação do admin)
-- Fluxo: dono da CMIG convida e-mail → pessoa se cadastra (User inativo) → admin
-- geral aprova (ativa o login) → dono vincula como colaborador (cmig_administrators).
-- Idempotente.

DECLARE
  e_table_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_table_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE user_invites (
      id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cmig_id             NUMBER,
      email               VARCHAR2(255) NOT NULL,
      invited_by_user_id  NUMBER NOT NULL,
      user_id             NUMBER,
      token               VARCHAR2(80) NOT NULL,
      status              VARCHAR2(20) DEFAULT 'pending_registration' NOT NULL,
      created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      resolved_at         TIMESTAMP,
      CONSTRAINT uq_user_invite_token UNIQUE (token),
      CONSTRAINT chk_user_invite_status CHECK (
        status IN ('pending_registration','pending_approval','active','rejected','expired')
      )
    )
  ]';
  EXECUTE IMMEDIATE 'CREATE INDEX idx_user_invite_email ON user_invites(email)';
  EXECUTE IMMEDIATE 'CREATE INDEX idx_user_invite_status ON user_invites(status)';
  DBMS_OUTPUT.PUT_LINE('Tabela user_invites criada.');
EXCEPTION
  WHEN e_table_exists THEN
    DBMS_OUTPUT.PUT_LINE('Tabela user_invites ja existe, continuando.');
END;
/
