-- 120_dce_emissao.sql — Emissão de DC-e (Declaração de Conteúdo Eletrônica) perfil Marketplace (ADR futuro)
--
-- A DC-e das contas de vendedor PESSOA FÍSICA (CPF) é emitida pela MIG no perfil "Marketplace"
-- (tpEmit=1): a MIG assina com o A1 do CNPJ dela, por conta e ordem do vendedor CPF (remetente).
-- Adiciona:
--   platform_cert_configs      — certificado A1 CENTRAL do assinante (marketplace), 1 por profile_type.
--                                 (o cert por CMIG continua em cmig_fiscal_config; este é o cert da MIG.)
--   order_dce                  — DC-e emitida por pedido (chave 44díg, protocolo, status, xml, dace).
--   cmig_fiscal_config.dce_authorized — autorização "por conta e ordem" do vendedor (default BLOQUEADO).
--
-- Idempotente: EXCEPTION WHEN e_exists (tabela -955 / coluna -1430).

DECLARE
  e_table_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_table_exists, -955);   -- ORA-00955: name already used
  e_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_col_exists, -1430);    -- ORA-01430: column already exists

  PROCEDURE run(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN e_table_exists THEN NULL;
    WHEN e_col_exists THEN NULL;
  END;
BEGIN
  -- Certificado A1 central do assinante (marketplace). profile_type único (ex.: 'marketplace_dce').
  run('CREATE TABLE platform_cert_configs (
        id                       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        profile_type             VARCHAR2(50) NOT NULL,
        cnpj                     VARCHAR2(18) NOT NULL,
        company_name             VARCHAR2(255) NOT NULL,
        site                     VARCHAR2(255),
        cert_path                VARCHAR2(255),
        cert_pass_encrypted      VARCHAR2(512),
        certificate_subject      VARCHAR2(500),
        certificate_uploaded_at  TIMESTAMP WITH TIME ZONE,
        certificate_expires_at   TIMESTAMP WITH TIME ZONE,
        created_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
        updated_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
        CONSTRAINT uq_pcc_profile UNIQUE (profile_type)
      )');

  -- DC-e emitida por pedido. Tabela PRÓPRIA (não reusa invoices — que é NF-e).
  run('CREATE TABLE order_dce (
        id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id      NUMBER NOT NULL,
        pack_id       VARCHAR2(50),
        shipment_id   VARCHAR2(50),
        chave         VARCHAR2(44),
        protocolo     VARCHAR2(30),
        serie         NUMBER,
        numero        NUMBER,
        status        VARCHAR2(20) DEFAULT ''draft'' NOT NULL,
        cstat         VARCHAR2(4),
        xmotivo       VARCHAR2(255),
        natureza      VARCHAR2(255),
        environment   VARCHAR2(12),
        signer_cnpj   VARCHAR2(18),
        emit_cpf      VARCHAR2(14),
        xml           CLOB,
        dace_path     VARCHAR2(1000),
        emitted_at    TIMESTAMP WITH TIME ZONE,
        created_at    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
        updated_at    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
        CONSTRAINT fk_order_dce_order FOREIGN KEY (order_id) REFERENCES orders(id)
      )');
  run('CREATE UNIQUE INDEX uq_order_dce_chave ON order_dce (chave)');
  run('CREATE INDEX ix_order_dce_order ON order_dce (order_id)');
  run('CREATE INDEX ix_order_dce_pack ON order_dce (pack_id)');

  -- Autorização "por conta e ordem" do vendedor. Default 0 = BLOQUEADO (não emite sem consentimento).
  run('ALTER TABLE cmig_fiscal_config ADD dce_authorized NUMBER(1) DEFAULT 0 NOT NULL');
  -- Numeração própria da DC-e (série + próximo número), por ambiente.
  run('ALTER TABLE cmig_fiscal_config ADD dce_serie NUMBER DEFAULT 1');
  run('ALTER TABLE cmig_fiscal_config ADD dce_next_number NUMBER DEFAULT 1');
  run('ALTER TABLE cmig_fiscal_config ADD dce_next_number_homolog NUMBER DEFAULT 1');
END;
/

COMMIT;
