-- 128_audit_events.sql
-- Auditoria de ações destrutivas: QUEM apagou o quê, quando e de onde.
--
-- Contexto: os anúncios importados de uma conta sumiram 4 vezes (22/06, 02/07, 08/07, 12/07).
-- Os logs mostraram DELETEs reais, um a cada ~1,4s, em ordem decrescente de id — um cliente
-- automatizado com login válido. Mas o sistema **não registrava o usuário**: só deu para chegar
-- ao IP. Sem isso, toda investigação vira arqueologia de log.
--
-- Idempotente: ignora ORA-00955 (nome já usado).

DECLARE
  e_ja_existe EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_ja_existe, -955);   -- ORA-00955: name is already used by an object

  PROCEDURE exec(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN e_ja_existe THEN NULL;
  END;
BEGIN
  exec('CREATE TABLE audit_events (
          id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id       NUMBER,
          user_email    VARCHAR2(255),
          action        VARCHAR2(60)  NOT NULL,   -- ex: anuncio.delete
          entity_type   VARCHAR2(40)  NOT NULL,   -- ex: product_listing
          entity_id     VARCHAR2(60),
          details       CLOB,                     -- snapshot do que foi apagado (JSON)
          ip            VARCHAR2(64),
          user_agent    VARCHAR2(400),
          created_at    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP
        )');
  exec('CREATE INDEX ix_audit_events_created ON audit_events (created_at)');
  exec('CREATE INDEX ix_audit_events_action  ON audit_events (action, entity_id)');
  COMMIT;
END;
/
