-- Migration 138: permissões de AÇÃO por perfil de acesso (ADR-0025 / Opção B).
--
-- Decompõe o "Papel Base API" em itens editáveis por perfil (como os menus). Cada linha concede
-- uma permission_key (do catálogo em services/action_permissions.py) a um perfil.
-- O SEED (backfill) é feito por script no deploy, a partir do base_role de cada perfil.
--
-- Idempotente: ORA-00955 (objeto já existe) é ignorado.

DECLARE
  e_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_exists, -955);
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE profile_action_permissions (
      id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      profile_id    NUMBER NOT NULL,
      permission_key VARCHAR2(100) NOT NULL,
      CONSTRAINT fk_pap_profile FOREIGN KEY (profile_id) REFERENCES user_profiles(id) ON DELETE CASCADE,
      CONSTRAINT uq_pap UNIQUE (profile_id, permission_key)
    )';
EXCEPTION
  WHEN e_exists THEN NULL;
END;
/
