-- Migration 143: Rastreabilidade de produtos (lote / validade / número serial / medicamento).
-- ADR-0027 — sub-ledger paralelo ADITIVO por cima do estoque escalar event-sourced.
--
-- Fase 1: schema apenas. Zero mudança de comportamento (produto default = não rastreável).
--   - Flags + campos de medicamento em catalog_products / cmig_products.
--   - product_lots  (saldo por lote, 5 baldes espelhando o escalar).
--   - product_serials (1 linha por unidade serial + status).
--   - invoice_item_lots / invoice_item_serials (rastro capturado da nota de ENTRADA).
--   - stock_lot_allocations (alocação de SAÍDA por item de pedido, com status).
--   - nfe_ncm_rastreavel (parâmetro: NCM x UF x vigência exige rastro/med — carregado da NT).
--
-- Idempotente: ORA-01430 (coluna já existe) e ORA-00955 (objeto já existe) são ignorados.

-- ============================================================
-- 1. Flags + medicamento em catalog_products (PG)
-- ============================================================
DECLARE
  e_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_col_exists, -1430);
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE catalog_products ADD (
    track_lot        NUMBER(1) DEFAULT 0 NOT NULL,
    track_expiry     NUMBER(1) DEFAULT 0 NOT NULL,
    track_serial     NUMBER(1) DEFAULT 0 NOT NULL,
    med_anvisa_code  VARCHAR2(13),
    med_pmc          NUMBER(15,2),
    med_exempt_reason VARCHAR2(255)
  )';
EXCEPTION
  WHEN e_col_exists THEN NULL;
END;
/

-- ============================================================
-- 2. Flags + medicamento em cmig_products (CMIG)
-- ============================================================
DECLARE
  e_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_col_exists, -1430);
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE cmig_products ADD (
    track_lot        NUMBER(1) DEFAULT 0 NOT NULL,
    track_expiry     NUMBER(1) DEFAULT 0 NOT NULL,
    track_serial     NUMBER(1) DEFAULT 0 NOT NULL,
    med_anvisa_code  VARCHAR2(13),
    med_pmc          NUMBER(15,2),
    med_exempt_reason VARCHAR2(255)
  )';
EXCEPTION
  WHEN e_col_exists THEN NULL;
END;
/

-- ============================================================
-- 3. product_lots — saldo por lote (CACHE derivado por replay; ADR-0027).
--    product_type: 'pg' | 'cmig' | 'variant_pg' | 'variant_cmig' (espelha stock_movements).
--    5 baldes espelham o escalar (product.py:44-48). balance sobe só no APTO (ADR-0009).
-- ============================================================
DECLARE
  e_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_exists, -955);
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE product_lots (
      id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      product_type  VARCHAR2(20) NOT NULL,
      product_id    NUMBER NOT NULL,
      lot_code      VARCHAR2(20) NOT NULL,
      mfg_date      DATE,
      expiry_date   DATE,
      balance                     NUMBER DEFAULT 0 NOT NULL,
      reserved                    NUMBER DEFAULT 0 NOT NULL,
      awaiting_return             NUMBER DEFAULT 0 NOT NULL,
      pending_validation          NUMBER DEFAULT 0 NOT NULL,
      unfit                       NUMBER DEFAULT 0 NOT NULL,
      created_at    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
      updated_at    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
      CONSTRAINT uq_product_lots UNIQUE (product_type, product_id, lot_code)
    )';
EXCEPTION
  WHEN e_exists THEN NULL;
END;
/

DECLARE
  e_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ix_product_lots_prod ON product_lots (product_type, product_id)';
EXCEPTION
  WHEN e_exists THEN NULL;
END;
/

DECLARE
  e_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ix_product_lots_expiry ON product_lots (expiry_date)';
EXCEPTION
  WHEN e_exists THEN NULL;
END;
/

-- ============================================================
-- 4. product_serials — 1 linha por unidade serial.
--    status: 'in_stock' | 'allocated' | 'shipped' | 'returned' | 'unfit' (DERIVADO do replay).
-- ============================================================
DECLARE
  e_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_exists, -955);
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE product_serials (
      id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      product_type  VARCHAR2(20) NOT NULL,
      product_id    NUMBER NOT NULL,
      serial        VARCHAR2(80) NOT NULL,
      lot_id        NUMBER,
      status        VARCHAR2(12) DEFAULT ''in_stock'' NOT NULL,
      order_id      NUMBER,
      created_at    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
      updated_at    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
      CONSTRAINT uq_product_serials UNIQUE (product_type, product_id, serial),
      CONSTRAINT fk_serial_lot FOREIGN KEY (lot_id) REFERENCES product_lots(id),
      CONSTRAINT fk_serial_order FOREIGN KEY (order_id) REFERENCES orders(id)
    )';
EXCEPTION
  WHEN e_exists THEN NULL;
END;
/

DECLARE
  e_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ix_product_serials_prod ON product_serials (product_type, product_id)';
EXCEPTION
  WHEN e_exists THEN NULL;
END;
/

-- ============================================================
-- 5. invoice_item_lots — rastro capturado na nota de ENTRADA (grupo <rastro>).
--    Um item pode ter N lotes (schema NFe 0..500).
-- ============================================================
DECLARE
  e_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_exists, -955);
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE invoice_item_lots (
      id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      invoice_item_id  NUMBER NOT NULL,
      n_lote           VARCHAR2(20) NOT NULL,
      q_lote           NUMBER(15,3) NOT NULL,
      d_fab            DATE,
      d_val            DATE,
      c_agreg          VARCHAR2(20),
      CONSTRAINT fk_iil_item FOREIGN KEY (invoice_item_id) REFERENCES invoice_items(id) ON DELETE CASCADE
    )';
EXCEPTION
  WHEN e_exists THEN NULL;
END;
/

DECLARE
  e_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ix_iil_item ON invoice_item_lots (invoice_item_id)';
EXCEPTION
  WHEN e_exists THEN NULL;
END;
/

-- ============================================================
-- 6. invoice_item_serials — serial capturado na nota de ENTRADA.
-- ============================================================
DECLARE
  e_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_exists, -955);
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE invoice_item_serials (
      id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      invoice_item_id  NUMBER NOT NULL,
      serial           VARCHAR2(80) NOT NULL,
      CONSTRAINT fk_iis_item FOREIGN KEY (invoice_item_id) REFERENCES invoice_items(id) ON DELETE CASCADE
    )';
EXCEPTION
  WHEN e_exists THEN NULL;
END;
/

DECLARE
  e_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ix_iis_item ON invoice_item_serials (invoice_item_id)';
EXCEPTION
  WHEN e_exists THEN NULL;
END;
/

-- ============================================================
-- 7. stock_lot_allocations — alocação de SAÍDA por item de pedido (FEFO/serial).
--    A baixa é ORDER-DRIVEN (ADR-0027); a emissão fiscal lê esta alocação (imutável).
--    status: 'allocated' | 'shipped' | 'awaiting_return' | 'pending_validation' | 'returned' | 'unfit'.
-- ============================================================
DECLARE
  e_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_exists, -955);
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE stock_lot_allocations (
      id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id      NUMBER NOT NULL,
      order_item_id NUMBER,
      product_type  VARCHAR2(20) NOT NULL,
      product_id    NUMBER NOT NULL,
      lot_id        NUMBER,
      serial_id     NUMBER,
      qty           NUMBER DEFAULT 0 NOT NULL,
      status        VARCHAR2(20) DEFAULT ''allocated'' NOT NULL,
      created_at    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
      updated_at    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
      CONSTRAINT fk_sla_order FOREIGN KEY (order_id) REFERENCES orders(id),
      CONSTRAINT fk_sla_lot FOREIGN KEY (lot_id) REFERENCES product_lots(id),
      CONSTRAINT fk_sla_serial FOREIGN KEY (serial_id) REFERENCES product_serials(id)
    )';
EXCEPTION
  WHEN e_exists THEN NULL;
END;
/

-- anti-duplicação: uma alocação por (item de pedido, lote) e por (item de pedido, serial).
DECLARE
  e_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uq_sla_item_lot ON stock_lot_allocations (order_item_id, lot_id)';
EXCEPTION
  WHEN e_exists THEN NULL;
END;
/

DECLARE
  e_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uq_sla_serial ON stock_lot_allocations (serial_id)';
EXCEPTION
  WHEN e_exists THEN NULL;
END;
/

DECLARE
  e_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ix_sla_order ON stock_lot_allocations (order_id)';
EXCEPTION
  WHEN e_exists THEN NULL;
END;
/

DECLARE
  e_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ix_sla_lot ON stock_lot_allocations (lot_id)';
EXCEPTION
  WHEN e_exists THEN NULL;
END;
/

-- ============================================================
-- 8. nfe_ncm_rastreavel — parâmetro fiscal (NCM x UF x vigência).
--    Carregado do anexo da NT vigente (NUNCA hardcode no código). uf NULL = nacional.
-- ============================================================
DECLARE
  e_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_exists, -955);
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE nfe_ncm_rastreavel (
      id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ncm             VARCHAR2(8) NOT NULL,
      uf              VARCHAR2(2),
      vig_ini         DATE,
      vig_fim         DATE,
      requires_rastro NUMBER(1) DEFAULT 1 NOT NULL,
      requires_med    NUMBER(1) DEFAULT 0 NOT NULL,
      created_at      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP
    )';
EXCEPTION
  WHEN e_exists THEN NULL;
END;
/

DECLARE
  e_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ix_ncm_rastreavel ON nfe_ncm_rastreavel (ncm)';
EXCEPTION
  WHEN e_exists THEN NULL;
END;
/
