-- Migration 47: Tabelas de atendimento (Central de Mensagens)
-- conversation_threads: threads unificadas (multi-plataforma)
-- conversation_messages: mensagens individuais por thread

DECLARE
    e_table_exists EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_table_exists, -955);
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE conversation_threads (
            id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            marketplace_account_id  NUMBER NOT NULL,
            platform                VARCHAR2(30) NOT NULL,
            thread_type             VARCHAR2(30) NOT NULL,
            platform_thread_id      VARCHAR2(100) NOT NULL,
            platform_order_id       VARCHAR2(100),
            buyer_platform_id       VARCHAR2(100),
            buyer_nickname          VARCHAR2(200),
            item_id                 VARCHAR2(100),
            item_title              VARCHAR2(500),
            status                  VARCHAR2(30) DEFAULT ''open'' NOT NULL,
            unread_count            NUMBER DEFAULT 0 NOT NULL,
            is_archived             NUMBER(1) DEFAULT 0 NOT NULL,
            last_message_at         TIMESTAMP WITH TIME ZONE,
            created_at              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            updated_at              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT fk_ct_account FOREIGN KEY (marketplace_account_id)
                REFERENCES marketplace_accounts(id) ON DELETE CASCADE,
            CONSTRAINT uq_thread_platform_id
                UNIQUE (platform, platform_thread_id, marketplace_account_id)
        )
    ';
    DBMS_OUTPUT.PUT_LINE('Tabela conversation_threads criada.');
EXCEPTION
    WHEN e_table_exists THEN
        DBMS_OUTPUT.PUT_LINE('Tabela conversation_threads ja existe.');
END;
/

DECLARE
    e_table_exists EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_table_exists, -955);
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE conversation_messages (
            id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            thread_id           NUMBER NOT NULL,
            platform_message_id VARCHAR2(200),
            from_role           VARCHAR2(20) NOT NULL,
            from_platform_id    VARCHAR2(100),
            text_content        CLOB,
            attachments_json    CLOB,
            is_read             NUMBER(1) DEFAULT 0 NOT NULL,
            sent_at             TIMESTAMP WITH TIME ZONE,
            synced_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            ai_suggested_text   CLOB,
            CONSTRAINT fk_cm_thread FOREIGN KEY (thread_id)
                REFERENCES conversation_threads(id) ON DELETE CASCADE,
            CONSTRAINT uq_platform_message_id UNIQUE (platform_message_id)
        )
    ';
    DBMS_OUTPUT.PUT_LINE('Tabela conversation_messages criada.');
EXCEPTION
    WHEN e_table_exists THEN
        DBMS_OUTPUT.PUT_LINE('Tabela conversation_messages ja existe.');
END;
/

-- Índices para performance

DECLARE
    e_idx_exists EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_idx_exists, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_ct_account_status ON conversation_threads(marketplace_account_id, status)';
    DBMS_OUTPUT.PUT_LINE('Indice idx_ct_account_status criado.');
EXCEPTION
    WHEN e_idx_exists THEN NULL;
END;
/

DECLARE
    e_idx_exists EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_idx_exists, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_ct_last_msg ON conversation_threads(last_message_at DESC)';
    DBMS_OUTPUT.PUT_LINE('Indice idx_ct_last_msg criado.');
EXCEPTION
    WHEN e_idx_exists THEN NULL;
END;
/

DECLARE
    e_idx_exists EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_idx_exists, -955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_cm_thread_sent ON conversation_messages(thread_id, sent_at)';
    DBMS_OUTPUT.PUT_LINE('Indice idx_cm_thread_sent criado.');
EXCEPTION
    WHEN e_idx_exists THEN NULL;
END;
/
