-- Migration 48: Configuração de IA para atendimento automático
-- ai_configs: configuração global (singleton)
-- cmig_ai_configs: instruções e modo por CMIG

DECLARE
    e_table_exists EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_table_exists, -955);
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE ai_configs (
            id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            provider            VARCHAR2(20) DEFAULT ''anthropic'' NOT NULL,
            api_key             VARCHAR2(2000),
            model_name          VARCHAR2(100) DEFAULT ''claude-sonnet-4-6'',
            global_instructions CLOB,
            is_active           NUMBER(1) DEFAULT 0 NOT NULL,
            created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
        )
    ';
    DBMS_OUTPUT.PUT_LINE('Tabela ai_configs criada.');
EXCEPTION
    WHEN e_table_exists THEN
        DBMS_OUTPUT.PUT_LINE('Tabela ai_configs ja existe.');
END;
/

DECLARE
    e_table_exists EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_table_exists, -955);
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE cmig_ai_configs (
            id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            cmig_id             NUMBER NOT NULL UNIQUE,
            custom_instructions CLOB,
            auto_respond        NUMBER(1) DEFAULT 0 NOT NULL,
            created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT fk_cmig_ai_cmig FOREIGN KEY (cmig_id)
                REFERENCES cmigs(id) ON DELETE CASCADE
        )
    ';
    DBMS_OUTPUT.PUT_LINE('Tabela cmig_ai_configs criada.');
EXCEPTION
    WHEN e_table_exists THEN
        DBMS_OUTPUT.PUT_LINE('Tabela cmig_ai_configs ja existe.');
END;
/
