-- Fase 2 — Trilha contábil: snapshots diários de estoque por produto.
-- Tabela alimentada por job APScheduler diário (tasks/daily_stock_reconcile.py).
-- Cada linha = saldo do produto no final do dia (BRT). Permite responder
-- "qual era meu estoque em 31/12?" e detectar drift entre cache e canônico.
-- Idempotente: bloco anônimo PL/SQL captura ORA-00955 (objeto já existe).

DECLARE
  e_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE stock_snapshots (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      snapshot_date DATE NOT NULL,
      product_type VARCHAR2(10) NOT NULL,    -- 'pg' | 'cmig'
      product_id NUMBER NOT NULL,
      cmig_id NUMBER NULL,                   -- denormalizado pra filtros
      sku VARCHAR2(100) NULL,                -- denormalizado pra relatório
      physical NUMBER DEFAULT 0 NOT NULL,
      reserved NUMBER DEFAULT 0 NOT NULL,
      available NUMBER DEFAULT 0 NOT NULL,
      awaiting_return NUMBER DEFAULT 0 NOT NULL,
      pending_validation NUMBER DEFAULT 0 NOT NULL,
      unfit NUMBER DEFAULT 0 NOT NULL,
      full_qty NUMBER DEFAULT 0 NOT NULL,
      full_reserved NUMBER DEFAULT 0 NOT NULL,
      drift_detected NUMBER(1) DEFAULT 0 NOT NULL,   -- 1 = cache divergiu do canônico
      drift_details VARCHAR2(500) NULL,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN e_obj_exists THEN NULL;
END;
/

DECLARE
  e_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE
    'CREATE UNIQUE INDEX uq_stock_snap_date_product '
    'ON stock_snapshots(snapshot_date, product_type, product_id)';
EXCEPTION
  WHEN e_obj_exists THEN NULL;
END;
/

DECLARE
  e_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_stock_snap_product_date '
    'ON stock_snapshots(product_type, product_id, snapshot_date)';
EXCEPTION
  WHEN e_obj_exists THEN NULL;
END;
/

DECLARE
  e_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_stock_snap_cmig_date '
    'ON stock_snapshots(cmig_id, snapshot_date)';
EXCEPTION
  WHEN e_obj_exists THEN NULL;
END;
/

COMMIT;
