-- Migration 93: Tabela de CFOPs configuráveis
-- Permite manutenção da lista de CFOPs sem deploy de código.
-- Idempotente: recria tabela apenas se não existir; seed apenas se estiver vazia.

DECLARE
  e_table_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_table_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE cfop_codes (
      id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code        VARCHAR2(4)   NOT NULL,
      description VARCHAR2(255) NOT NULL,
      direction   VARCHAR2(3)   NOT NULL,
      notes       VARCHAR2(500),
      is_active   NUMBER(1)     DEFAULT 1 NOT NULL,
      created_at  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT uq_cfop_code    UNIQUE (code),
      CONSTRAINT chk_cfop_dir    CHECK (direction IN ('in', 'out'))
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('Tabela cfop_codes criada.');
EXCEPTION
  WHEN e_table_exists THEN
    DBMS_OUTPUT.PUT_LINE('Tabela cfop_codes ja existe, continuando.');
END;
/

-- Seed: insere apenas se a tabela estiver vazia
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM cfop_codes;
  IF v_count > 0 THEN
    DBMS_OUTPUT.PUT_LINE('Seed ignorado: tabela cfop_codes ja possui dados.');
    RETURN;
  END IF;

  -- ────────────────────────────────────────────────────────────────
  -- ENTRADAS (1xxx = intra-estado, 2xxx = interestadual, 3xxx = exterior)
  -- ────────────────────────────────────────────────────────────────
  INSERT INTO cfop_codes (code, description, direction) VALUES ('1102', 'Compra para comercialização (intra-estado)', 'in');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('1113', 'Compra para comercialização de mercadoria usada (intra-estado)', 'in');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('1152', 'Transferência para comercialização (intra-estado)', 'in');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('1201', 'Devolução de venda de produto industrializado (intra-estado)', 'in');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('1202', 'Devolução de venda de mercadoria adquirida/recebida de terceiros (intra-estado)', 'in');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('1403', 'Compra para comercialização em operação com ST (intra-estado)', 'in');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('1411', 'Devolução de venda de mercadoria adquirida de terceiros em operação com ST (intra-estado)', 'in');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('1551', 'Compra de bem para o Ativo Imobilizado (intra-estado)', 'in');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('1556', 'Compra de material para uso ou consumo (intra-estado)', 'in');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('1910', 'Entrada de bonificação, doação ou brinde (intra-estado)', 'in');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('1949', 'Outra entrada de mercadoria não especificada (intra-estado)', 'in');

  INSERT INTO cfop_codes (code, description, direction) VALUES ('2102', 'Compra para comercialização (interestadual)', 'in');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('2113', 'Compra para comercialização de mercadoria usada (interestadual)', 'in');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('2152', 'Transferência para comercialização (interestadual)', 'in');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('2201', 'Devolução de venda de produto industrializado (interestadual)', 'in');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('2202', 'Devolução de venda de mercadoria adquirida/recebida de terceiros (interestadual)', 'in');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('2403', 'Compra para comercialização em operação com ST (interestadual)', 'in');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('2411', 'Devolução de venda de mercadoria adquirida de terceiros em operação com ST (interestadual)', 'in');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('2551', 'Compra de bem para o Ativo Imobilizado (interestadual)', 'in');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('2556', 'Compra de material para uso ou consumo (interestadual)', 'in');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('2910', 'Entrada de bonificação, doação ou brinde (interestadual)', 'in');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('2949', 'Outra entrada de mercadoria não especificada (interestadual)', 'in');

  INSERT INTO cfop_codes (code, description, direction) VALUES ('3102', 'Compra para comercialização (importação do exterior)', 'in');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('3202', 'Devolução de venda de mercadoria (exportação)', 'in');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('3556', 'Compra de material para uso ou consumo (importação)', 'in');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('3949', 'Outra entrada de mercadoria importada não especificada', 'in');

  -- ────────────────────────────────────────────────────────────────
  -- SAÍDAS (5xxx = intra-estado, 6xxx = interestadual, 7xxx = exterior)
  -- ────────────────────────────────────────────────────────────────
  INSERT INTO cfop_codes (code, description, direction) VALUES ('5102', 'Venda de mercadoria adquirida ou recebida de terceiros (intra-estado)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('5103', 'Venda de produto industrializado (intra-estado)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('5113', 'Venda de mercadoria adquirida de terceiros — mercadoria usada (intra-estado)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('5152', 'Transferência de mercadoria adquirida ou recebida de terceiros (intra-estado)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('5202', 'Devolução de compra de mercadoria adquirida/recebida de terceiros (intra-estado)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('5403', 'Venda de mercadoria com ST — como substituto tributário (intra-estado)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('5405', 'Venda de mercadoria adquirida com ST — como contribuinte substituído (intra-estado)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('5411', 'Devolução de compra de mercadoria adquirida com ST (intra-estado)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('5551', 'Venda de bem do Ativo Imobilizado (intra-estado)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('5556', 'Transferência de material de uso ou consumo (intra-estado)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('5910', 'Retorno de mercadoria remetida para conserto ou reparo (intra-estado)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('5911', 'Remessa de amostra grátis (intra-estado)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('5912', 'Remessa de mercadoria para demonstração (intra-estado)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('5913', 'Simples remessa (intra-estado)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('5916', 'Remessa em consignação mercantil (intra-estado)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('5917', 'Venda de mercadoria recebida em consignação mercantil (intra-estado)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('5949', 'Outra saída de mercadoria ou prestação de serviço não especificada (intra-estado)', 'out');

  INSERT INTO cfop_codes (code, description, direction) VALUES ('6102', 'Venda de mercadoria adquirida ou recebida de terceiros (interestadual)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('6103', 'Venda de produto industrializado (interestadual)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('6113', 'Venda de mercadoria adquirida de terceiros — mercadoria usada (interestadual)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('6152', 'Transferência de mercadoria adquirida ou recebida de terceiros (interestadual)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('6202', 'Devolução de compra de mercadoria adquirida/recebida de terceiros (interestadual)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('6403', 'Venda de mercadoria com ST — como substituto tributário (interestadual)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('6405', 'Venda de mercadoria adquirida com ST — como contribuinte substituído (interestadual)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('6411', 'Devolução de compra de mercadoria adquirida com ST (interestadual)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('6551', 'Venda de bem do Ativo Imobilizado (interestadual)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('6556', 'Transferência de material de uso ou consumo (interestadual)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('6910', 'Retorno de mercadoria remetida para conserto ou reparo (interestadual)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('6911', 'Remessa de amostra grátis (interestadual)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('6912', 'Remessa de mercadoria para demonstração (interestadual)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('6913', 'Simples remessa (interestadual)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('6916', 'Remessa em consignação mercantil (interestadual)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('6917', 'Venda de mercadoria recebida em consignação mercantil (interestadual)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('6949', 'Outra saída de mercadoria ou prestação de serviço não especificada (interestadual)', 'out');

  INSERT INTO cfop_codes (code, description, direction) VALUES ('7102', 'Venda de mercadoria adquirida ou recebida de terceiros (exportação)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('7103', 'Venda de produto industrializado (exportação)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('7202', 'Devolução de compra de mercadoria importada (exportação)', 'out');
  INSERT INTO cfop_codes (code, description, direction) VALUES ('7949', 'Outra saída de mercadoria para o exterior não especificada', 'out');

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Seed de cfop_codes inserido: ' || SQL%ROWCOUNT || ' registros.');
END;
/
