-- Migration 94: Tabela de alíquotas ICMS por UF
-- Resolve lacuna L1: tax_calculator usava 18% fixo intra / 12% fixo inter.
-- Seed: 27 alíquotas intra-estaduais (CONFAZ 2024).
-- Regras interestaduais SS↔SS (12%) e SS→outros (7%) são aplicadas por código
-- em icms_table.py; linhas específicas nesta tabela sobrescrevem o padrão.

DECLARE
  e_table_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_table_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE icms_rates (
      id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      uf_origin   VARCHAR2(2) NOT NULL,
      uf_dest     VARCHAR2(2) NOT NULL,
      aliquota    NUMBER(5,2) NOT NULL,
      valid_from  DATE        DEFAULT SYSDATE NOT NULL,
      valid_to    DATE,
      is_active   NUMBER(1)   DEFAULT 1 NOT NULL,
      notes       VARCHAR2(255),
      CONSTRAINT uq_icms_rate UNIQUE (uf_origin, uf_dest, valid_from)
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('Tabela icms_rates criada.');
EXCEPTION
  WHEN e_table_exists THEN
    DBMS_OUTPUT.PUT_LINE('Tabela icms_rates ja existe, continuando.');
END;
/

-- Seed intra-estadual (uf_origin = uf_dest) — apenas se vazio
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM icms_rates;
  IF v_count > 0 THEN
    DBMS_OUTPUT.PUT_LINE('Seed ignorado: icms_rates ja possui dados.');
    RETURN;
  END IF;

  -- ── Intra-estaduais (alíquota geral por UF — CONFAZ 2024) ──────────────
  -- Fontes: decretos estaduais vigentes. Alíquotas gerais para mercadorias.
  -- Revisar anualmente e ao receber atualização do CONFAZ.
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('AC','AC', 17, 'Lei 1.418/2003');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('AL','AL', 19, 'Lei 5.900/96 alt.');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('AM','AM', 20, 'Lei 2.826/2003');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('AP','AP', 18, 'Lei 0400/97');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('BA','BA', 21, 'Lei 7.014/96');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('CE','CE', 20, 'Lei 12.670/96');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('DF','DF', 20, 'Lei 1.254/96');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('ES','ES', 17, 'Lei 7.000/2001');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('GO','GO', 17, 'Lei 11.651/91');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('MA','MA', 22, 'Lei 7.799/02');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('MG','MG', 18, 'Lei 6.763/75');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('MS','MS', 17, 'Lei 1.810/97');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('MT','MT', 17, 'Lei 7.098/98');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('PA','PA', 17, 'Lei 5.530/89');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('PB','PB', 18, 'Lei 6.379/96');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('PE','PE', 20.5, 'Lei 15.730/2016');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('PI','PI', 21, 'Lei 4.257/89');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('PR','PR', 19.5, 'Lei 11.580/96');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('RJ','RJ', 20, 'Lei 2.657/96');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('RN','RN', 18, 'Lei 6.968/96');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('RO','RO', 17.5, 'Lei 688/96');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('RR','RR', 17, 'Lei 59/93');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('RS','RS', 17, 'Lei 8.820/89');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('SC','SC', 17, 'Lei 10.297/96');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('SE','SE', 19, 'Lei 3.796/96');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('SP','SP', 18, 'Lei 6.374/89');
  INSERT INTO icms_rates (uf_origin, uf_dest, aliquota, notes) VALUES ('TO','TO', 20, 'Lei 1.287/2001');

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Seed icms_rates: 27 aliquotas intra-estaduais inseridas.');
END;
/
