-- Migration 95: Tabela de códigos NCM para validação
-- Resolve lacuna L7: aceitar qualquer 8 dígitos causava rejeição SEFAZ código 562.
-- Seed: ~80 NCMs mais frequentes em e-commerce BR.
-- Para importar a TEC completa (~10k registros), use o endpoint admin /ncm/import-csv.

DECLARE
  e_table_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_table_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE ncm_codes (
      id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code        VARCHAR2(8)   NOT NULL,
      description VARCHAR2(500) NOT NULL,
      section     VARCHAR2(5),
      chapter     VARCHAR2(2),
      ipi_rate    NUMBER(5,2),
      is_active   NUMBER(1)     DEFAULT 1 NOT NULL,
      CONSTRAINT uq_ncm_code UNIQUE (code)
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('Tabela ncm_codes criada.');
EXCEPTION
  WHEN e_table_exists THEN
    DBMS_OUTPUT.PUT_LINE('Tabela ncm_codes ja existe, continuando.');
END;
/

-- Seed: NCMs mais comuns em e-commerce / dropshipping
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ncm_codes;
  IF v_count > 0 THEN
    DBMS_OUTPUT.PUT_LINE('Seed ignorado: ncm_codes ja possui dados.');
    RETURN;
  END IF;

  -- Eletrônicos e Informática
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('84713012','Computadores portáteis (notebooks)', '84');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('84714900','Outras máquinas automáticas para processamento de dados', '84');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('84716000','Unidades de entrada (teclado, mouse)', '84');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('84717014','Disco de estado sólido (SSD)', '84');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('84718010','Monitor de vídeo', '84');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('84733099','Partes e acessórios de computadores', '84');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('85171231','Smartphones / telefones celulares', '85');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('85176299','Outros aparelhos para transmissão / recepção de dados', '85');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('85258090','Câmeras digitais e filmadoras', '85');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('85285291','Monitores e televisores LCD/LED', '85');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('85299090','Partes de televisores e monitores', '85');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('85423100','Processadores (chips / CPUs)', '85');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('84733019','Placas de vídeo e memória RAM', '84');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('84714100','Microcomputadores de mesa (desktop)', '84');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('85122010','Roteadores e switches', '85');

  -- Áudio e Periféricos
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('85183000','Fones de ouvido e headsets', '85');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('85182200','Alto-falantes e caixas de som', '85');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('84748010','Impressoras', '84');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('84439990','Cartuchos e toners de impressora', '84');

  -- Eletrodomésticos
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('84145100','Ventiladores domésticos', '84');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('84151012','Ar-condicionado (split)', '84');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('85167200','Torradeiras elétricas', '85');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('85167900','Outros aparelhos eletrodomésticos de aquecimento', '85');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('84513000','Máquinas de lavar roupa (uso doméstico)', '84');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('84221100','Máquinas de lavar louça (uso doméstico)', '84');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('84181000','Combinados (geladeiras com freezer)', '84');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('84184000','Freezers verticais e horizontais', '84');

  -- Vestuário e Calçados
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('61051000','Camisetas de malha de algodão', '61');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('61091000','Camisetas polo e similares', '61');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('61103000','Blusas de trico', '61');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('61149000','Roupas esportivas e leggings', '61');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('62034200','Calças jeans masculinas', '62');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('62044200','Calças jeans femininas', '62');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('62052000','Camisas sociais', '62');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('64021900','Tênis e calçados de borracha/plástico', '64');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('64041100','Tênis com sola de borracha e cabedal têxtil', '64');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('64051000','Chinelos e sandálias', '64');

  -- Artigos para casa e decoração
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('94016900','Cadeiras e assentos', '94');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('94029000','Móveis plásticos', '94');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('94036000','Outros móveis de madeira', '94');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('94039090','Outros móveis e suas partes', '94');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('63049000','Enxoval de cama, mesa e banho', '63');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('94054090','Luminárias e abajures', '94');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('73218100','Churrasqueiras e fogões a gás de uso doméstico', '73');

  -- Esporte e lazer
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('95063900','Bolas esportivas', '95');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('95069100','Academias e equipamentos esportivos', '95');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('95049000','Artigos para jogos de salão', '95');

  -- Brinquedos
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('95030000','Brinquedos em geral', '95');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('95044000','Baralhos e jogos de cartas', '95');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('95045000','Videogames e consoles', '95');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('95049090','Jogos de vídeo (cartucho/CD)', '95');

  -- Cosméticos e higiene pessoal
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('33051000','Xampus', '33');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('33052000','Preparações para ondulação ou alisamento', '33');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('33030000','Perfumes e águas-de-colônia', '33');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('33049900','Outros produtos de beleza', '33');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('33061000','Dentifrícios', '33');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('33071000','Preparações para barbear', '33');

  -- Alimentos e suplementos
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('21069090','Complementos alimentares e suplementos', '21');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('04021000','Leite em pó', '04');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('09011110','Café em grão (não torrado)', '09');

  -- Ferramentas e materiais de construção
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('82055900','Ferramentas manuais diversas', '82');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('84672900','Ferramentas elétricas (furadeiras, parafusadeiras)', '84');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('85319090','Equipamentos de segurança eletrônica', '85');

  -- Livros e papelaria
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('49011000','Livros impressos', '49');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('49019900','Outros livros, brochuras', '49');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('48201000','Cadernos e blocos de notas', '48');

  -- Automóveis e motos (acessórios)
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('87089990','Outras partes e acessórios de veículos', '87');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('40111000','Pneus novos para automóveis', '40');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('87141000','Acessórios para motocicletas', '87');

  -- Embalagens
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('48191000','Caixas de papelão / papelão ondulado', '48');
  INSERT INTO ncm_codes (code, description, chapter) VALUES ('39232990','Sacos plásticos', '39');

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Seed ncm_codes: registros de NCMs de e-commerce inseridos.');
END;
/
