-- Migration 96: Log de sincronização DFe por CMIG (dead-letter / auditoria)
-- Resolve lacuna L5: scheduler DFe sem log, retry ou alerta de falha por CMIG.

DECLARE
  e_table_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_table_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE dfe_sync_log (
      id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cmig_id             NUMBER NOT NULL,
      started_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      finished_at         TIMESTAMP,
      status              VARCHAR2(10) DEFAULT 'running' NOT NULL,
      invoices_created    NUMBER DEFAULT 0,
      invoices_skipped    NUMBER DEFAULT 0,
      errors_count        NUMBER DEFAULT 0,
      error_detail        VARCHAR2(4000),
      consecutive_errors  NUMBER DEFAULT 0,
      CONSTRAINT chk_dfe_status CHECK (status IN ('running','ok','error'))
    )
  ]';
  EXECUTE IMMEDIATE 'CREATE INDEX idx_dfe_log_cmig ON dfe_sync_log(cmig_id, started_at)';
  DBMS_OUTPUT.PUT_LINE('Tabela dfe_sync_log criada.');
EXCEPTION
  WHEN e_table_exists THEN
    DBMS_OUTPUT.PUT_LINE('Tabela dfe_sync_log ja existe, continuando.');
END;
/
